// src/utils/SubCategories.ts

export const PLACE_SUBCATEGORIES = [
  "restaurants",
  "cafes",
  "bakeries",
  "street food",
  "juice & smoothie shops",
  "sweet shops",
  "ice cream parlours",
  "hotels",
  "resorts",
  "lodges",
  "guest houses",
  "grocery stores",
  "supermarkets",
  "clothing stores",
  "shoe shops",
  "mobile stores",
  "electronics shops",
  "jewellery stores",
  "stationery shops",
  "schools",
  "colleges",
  "coaching centres",
  "courier offices",
  "delivery services",
  "parcel services",
  "hospitals",
  "clinics",
  "pharmacies / medical shops",
];

export const WORKER_SUBCATEGORIES = [
  "plumbers",
  "electricians",
  "carpenters",
  "painters",
  "ac repair",
  "fridge repair",
  "washing machine repair",
  "home appliance repair",
  "maids services",
  "cook services",
  "babysitters",
  "elderly care",
  "car repair / service",
  "bike repair",
  "towing services",
  "mobile repair",
  "laptop repair",
  "computer & laptop repair",
  "construction labor",
  "cleaning helpers",
  "garden workers",
];

// ✅ Add this mapping for main categories → subcategories
export const PLACE_CATEGORY_MAP: Record<string, string[]> = {
  "food & dining": [
    "restaurants",
    "cafes",
    "bakeries",
    "street food",
    "juice & smoothie shops",
    "sweet shops",
    "ice cream parlours",
  ],
  "travel / stay": ["hotels", "resorts", "lodges", "guest houses"],
  shopping: [
    "grocery stores",
    "supermarkets",
    "clothing stores",
    "shoe shops",
    "mobile stores",
    "electronics shops",
    "jewellery stores",
    "stationery shops",
  ],
  education: ["schools", "colleges", "coaching centres"],
  "transport / logistics": ["courier offices", "delivery services", "parcel services"],
  health: ["hospitals", "clinics", "pharmacies / medical shops"],
};
